### ISSUE TITLE
Accessor functions: returned objects should have names

### ISSUE THREAD

**Issue by Jfortin1** [Jfortin1/crisprDesign#4]

**Comment by ltHobbes** [comment]
names should be revised (currently duplicated): snps()
no names: alignments(), onTargets(), offTargets()
enzymeAnnotation(), snps() also has ID column, which is identical to names

**Comment by ltHobbes** [comment]
The following functions currently return objects without row names:

- `alignments()`
- 'onTargets()`
- `offTargets()`

Meanwhile, `enzymeAnnotation()` returns a named object with an `ID` column that is identical to the row names. This isn't a problem, but we may want to be consistent whether `ID` is provided across accessors and decide whether it is necessary when `rownames` contains the same info.

`snps()` also returns a similar `ID` column, but the row names are duplicated (e.g. `spacer_596.spacer_596`). Accessing SNPs directly with `guideSet$snps` does not return duplicated row names.

**Comment by ltHobbes** [comment]
Fixed the name duplication with `snps()`.

**Comment by ltHobbes** [comment]
`alignments()`, `onTargets()`, and `offTargets()` return `GRanges` objects, while `enzymeAnnotation()` and `snps()` return `DataFrame` objects (`snps()` may be better suited to return a `GRanges` or `GPos`). For both `GRanges` and `DataFrame` objects, duplicated (row) names are intentionally permissible, so we would not encounter any errors or, curiously, even warning messages for duplicated row names.

From my understanding, the authors find this behavior to have some drawbacks (hashing; doesn't behave like a Python `dict`), but is still the preferable choice:

- it allows intuitive relationships for the user, such as `GRanges` of exons whose names have the same `gene_id` or `gene_symbol`
- it is consistent with R permitting `lists` and `vectors` to have duplicated names (however, some also don't like this behavior)
- it is much easier to permit than to guard against every possible permutation that could result in duplicated names

`data.frame` objects do not permit duplicated row names, but the user is given an argument to set their own row names in `as.data.frame`.

-----------------

Adding an `id` column of names avoids the problems of duplicated names. If it always (or by default) contains values of the pattern `spacer_X`, perhaps we can name it `spacer_id` to prevent confusion when multiple `id` columns are present.

Another option is to include an argument in the accessor functions, such as `use.names`. If `TRUE`, the returned `GRanges` or `DataFrame` object has row names, possibly duplicated; if `FALSE`, the names of returned object are `NULL`, but is prepended by an `id` column.

**Comment by ltHobbes** [comment]
Example of option implementing `use.names` argument:
```
> snps(gs, use.names=TRUE)
DataFrame with 4 rows and 9 columns
                    rs   rs_site rs_site_rel     allele_ref   allele_minor MAF_1000G MAF_TOPMED        type    length
           <character> <integer>   <numeric> <DNAStringSet> <DNAStringSet> <numeric>  <numeric> <character> <integer>
spacer_596  rs55923022    138989          -8              C              T   0.13120    0.12527         snp         1
spacer_608  rs56204927    139036           0              C              G   0.65620    0.62553         snp         1
spacer_524  rs77474006    138905         -10              G              C   0.05691    0.04888         snp         1
spacer_10   rs17852242     66973         -17              A              T   0.07029    0.14048         snp         1

> snps(gs, use.names=FALSE)
DataFrame with 4 rows and 10 columns
    spacer_id          rs   rs_site rs_site_rel     allele_ref   allele_minor MAF_1000G MAF_TOPMED        type    length
  <character> <character> <integer>   <numeric> <DNAStringSet> <DNAStringSet> <numeric>  <numeric> <character> <integer>
1  spacer_596  rs55923022    138989          -8              C              T   0.13120    0.12527         snp         1
2  spacer_608  rs56204927    139036           0              C              G   0.65620    0.62553         snp         1
3  spacer_524  rs77474006    138905         -10              G              C   0.05691    0.04888         snp         1
4   spacer_10  rs17852242     66973         -17              A              T   0.07029    0.14048         snp         1
```

The spacer IDs are always preserved.

**Comment by ltHobbes** [comment]
Implemented `use.names` argument on the **accessors** branch. Affected functions:

- `snps`
- `alignments`
- `onTargets`
- `offTargets`
- `geneAnnotation`
- `tssAnnotation`
- `enzymeAnnotation`
