### ISSUE TITLE
Add checks For alignments accessor functions (columnName argument)

### ISSUE THREAD

**Issue by Jfortin1** [Jfortin1/crisprDesign#5]
- Want to check that the object stored in `columnName` is an actual alignments output. --> write check function

**Comment by ltHobbes** [comment]
Check function requires alignments GRangesList column to have the following column names,

```c("spacer", "protospacer", "pam", "pam_site", "n_mismatches", "canonical", "cut_site")```

which are always output from `addSpacerAlignments`.
